name: planets
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  kt_dart: ^1.1.0
  riverpod_annotation: ^2.6.1
  xml: ^6.5.0
  xml2json: ^6.2.5
dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  
flutter:
  uses-material-design: true
  assets:
    - assets/  
    - assets/constellations/
